---
- name: Install http server     # name of the playbook
  hosts: web                     # target group defined in the inventory file 
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest
    - name: Start and enable httpd service
      yum:
        name: httpd
        state: latest
        enabled: true
    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <body>
          <h1>Practice Project using AWS, Terraform, Ansible, Github Actions</h1>
          <p>Ansible is working</p>

          </body>
          </html>
        